permaweb/ao

servers/cu/src/domain/api/readState.js
servers/cu/src/domain/utils.js
servers/cu/src/domain/utils.test.js

The CU already re-uses pending readState evaluation streams if the requests are requesting to evaluate a process up to the same message.
This adds a further optimization, that will "chain" readState operations, which should help with cascading readState evals.
For example:
If an evaluation stream for process X up to message 10 is currently running, then a new requests for process X up to message 11 arrives, it will simply chain off of the work being performed by the pending evaluation stream:
```
processAMessage10---->working--->DONE--|
later----processAMessage11---------|-->eval diff (1 msg)--> DONE--|
later------processAMessage12------------------------------------|-->eval diff (1 msg)--> DONE
```
Without this, because each eval stream doesn't cache the memory until the end of the eval …

feat(cu): chain off earlier pending readState eval streams to prevent duplicate work

---

connect/package-lock.json
connect/package.json
connect/src/client/node/wallet.js
connect/src/client/node/wallet.test.js

Total hack, but can't figure out another way for Node module resolution to play nicely with `esbuild` artifact and tests

build(connect): guard on default to get importing warp-arbundles to work

---

servers/cu/src/domain/client/ao-su.js
servers/cu/src/domain/dal.js
servers/cu/src/domain/index.js
servers/cu/src/domain/lib/loadMessageMeta.js
servers/cu/src/domain/lib/loadMessageMeta.test.js
servers/cu/src/domain/lib/loadMessages.js
servers/cu/src/domain/lib/loadProcess.js
servers/cu/src/domain/lib/loadProcess.test.js

This PR makes it so the CU does not depend as much on the gateway for locating a process on a scheduler unit. Instead, the CU will leverage it's cache to obtain the `Scheduler` tag for the process and then only load the `Scheduler-Location` record from gateway (if not already cached.
This hedges against finality or backup issues with the gateway, especially for new processes, since we've observed that the gateway will sometimes not return a bona-fide ao process because of two reasons:
- finality
- optimistic cache expires before unbundling and indexing can be performed
TL;DR: this greatly reduces the dependency of the CU on the gateway, more proactively utilizing it's many caching layers.

feat(cu): use process cache more proactively to locate scheduler, hedging against gateway finality issues

---

.gitignore
servers/ur/.env.example
servers/ur/README.md
servers/ur/src/app.js
servers/ur/src/config.js
servers/ur/src/domain.js
servers/ur/src/proxy.js
servers/ur/src/redirect.js
servers/ur/src/routes/byAoUnit.js
servers/ur/src/routes/cu.js
servers/ur/src/routes/mu.js

Adds `STRATEGY` environment variable, with default value of `proxy`. This maintains the current behavior.
With `STRATEGY=redirect`, the UR to return HTTP 307 redirects instead.
Closes #539.

feat(ur): add `redirect` strategy

---

scheduler-utils/README.md
scheduler-utils/src/index.common.js
scheduler-utils/src/locate.js
scheduler-utils/src/locate.test.js

This was the root cause of #543 
The url obtained from the redirect, which is process specific, was being cached for the `owner`. So when calling `raw` on `scheduler-utils`, it was returning the cached redirected url for the specific process. This would cause subsequent processes to `404` on the scheduler.
This PR also adds the ability to provide a`schedulerHint` to `locate`, which will cause it to skip querying for the process, and instead query directly for the `Scheduler-Location`, utilizing it's internal in memory cache.

fix(scheduler-utils): do not cache the redirected url in the byOwner cache

---

servers/cu/src/domain/client/ao-su.js
servers/cu/src/domain/client/ao-su.test.js
servers/cu/src/domain/client/worker.js
servers/cu/src/domain/client/worker.test.js
servers/cu/src/domain/index.js
servers/cu/src/domain/lib/evaluate.js
servers/cu/src/domain/lib/gatherResults.js
servers/cu/src/domain/lib/hydrateMessages.js
servers/cu/src/domain/lib/hydrateMessages.test.js
servers/cu/src/domain/lib/loadMessages.js
servers/cu/src/domain/model.js

Closes #556 
This PR:
- implements `Assignment` message hydration according to `aopv0.1` 
- If an `Assignment` references a message on chain, then the CU will download, and _overwrite_ ie. "hydrate" the message data to be sent to the process using the that data
- Unlike `Load` messages
- Interop between legacy and new response shapes from SU, according to what's described in #563
- loading meta aka. `Assignment` from the SU `/{messageTxId}?process-id=...`
- loading process message stream `/{processTxId}?process-id=...`
The interoperability of legacy and new response shape will enable deploying the CUs separately, without a coordinated SU deployment. Then at any point, the SUs serving the new shape can be deployed, and the CU will "switch" to using the new mapping strategy. Finally, once …

Implement Assignment `aopv0.1` in CU

---

servers/mu/.env.example
servers/mu/README.md
servers/mu/cranker/src/config.js
servers/mu/cranker/src/index.common.js
servers/mu/src/config.js
servers/mu/src/domain/index.js

This change is brought about by changes in scheduler-utils@0.0.16.
And we're mimicing similar changes in the CU.

fix(mu): use graphql_url instead of gateway_url

---

servers/cu/src/domain/client/ao-evaluation.js
servers/cu/src/domain/client/ao-evaluation.test.js
servers/cu/src/domain/client/ao-process.js
servers/cu/src/domain/client/sqlite.js
servers/cu/src/domain/dal.js
servers/cu/src/domain/index.js
servers/cu/src/domain/lib/evaluate.js
servers/cu/src/domain/lib/evaluate.test.js

Needed as part of `aop1` to deduplicate assignments and pushed messages.
`messages` is a separate table which will make hydration from a `Checkpoint`, disregarding evluations, simpler

feat(cu): dedupe duplicate assignments and duplicate pushes

---

servers/cu/src/app.js
servers/cu/src/domain/index.js

feat(cu): `process.exit()` after `SIGTERM` handlers #606

---

scheduler-utils/package-lock.json
scheduler-utils/package.json
scheduler-utils/src/client/gateway.js
scheduler-utils/src/client/gateway.test.js
scheduler-utils/src/client/in-memory.js
scheduler-utils/src/client/in-memory.test.js
scheduler-utils/src/client/scheduler.test.js
scheduler-utils/src/dal.js
scheduler-utils/src/locate.js
scheduler-utils/src/locate.test.js
scheduler-utils/src/raw.js
scheduler-utils/src/raw.test.js
scheduler-utils/src/validate.js
scheduler-utils/src/validate.test.js

We were running into issues as a result of nothing enforcing side-effect contracts. So this PR enforces them using `zod` similar to other ao libs (`aoconnect`) and ao units. The schemas are invoked by BL and used in side-effects tests, so that we can be confident that all layers are adhering to the data contract.
This also adds `ttl` to the `byOwner` cache, so that it can be used on the `schedulerHint` branch in `locate`.
Finally, this remaps `{ ..., owner }` -> `{ ..., address }` in data contracts, for ease of mapping.

fix(scheduler-utils): wrap all side effects in schemas. Store ttl in byOwner cache

---

connect/src/client/ao-cu.js
connect/src/dal.js
connect/src/lib/results/index.js
connect/src/lib/results/query.js
connect/src/lib/results/query.test.js
connect/src/lib/results/verify-input.js
connect/src/lib/results/verify-input.test.js

The docs + the ao-cu implementation talk about/use a `limit` property which was missing from the results api.
The zod object also had a property `limit`, although it was marked as a string. I've changed this to be a number.

fix(connect): add missing limit arg to results api

---

servers/cu/src/domain/api/dryRun.js
servers/cu/src/routes/dryRun.js

Closes #674 
`readState` is no longer invoked by `dryRun`. Instead `dryRun` simply loads the process (which includes caching process, loading it's latest memory, and priming the LRU In-Memory cache if needed), loads the module (which includes caching),
then finally evaluates the single dryRun message

feat(cu): dry-run only uses latest memory for process to perform dry-run evals #674

---

servers/ur/src/routes/mu.js

This PR makes it so that the MU route will conditionally consume the body based on whether or not the `assign` query parameter is provided. In this case, there is no body to consume. Additionally, the `processId` is available as a `process-id` query parameter, and so can be extracted from there.

fix(ur): do not parse body on root mu POST route, if request is an assignment #697

---

servers/cu/src/domain/utils.js

fix(cu): ensure thrown error in backoff will always be encapsulated by promise chain #729

---

servers/su/migrations/2024-05-29-143054_messages_indexing/down.sql
servers/su/migrations/2024-05-29-143054_messages_indexing/up.sql

Adds migrations to remove the previous index for process_id and adds a new index combining process_id and timestamp. This speeds up queries to retrieve messages significantly.

perf(su): alter message table index for faster reads

---

servers/mu/src/domain/clients/worker.js

References #661, #743
Fixes try catch block in MU worker. Needs to be a .catch since work happening asynchronously

fix(mu): change try catch to .catch in mu worker

---

loader/src/formats/wasm64-emscripten.cjs
package-lock.json

Updated the wasm64 format to make weavedrive optional

feat(loader): weavedrive should be optional for wasm64

---

servers/cu/package-lock.json
servers/cu/package.json

Just some housekeeping. `10` of `better-sqlite3` ships with Node 22 bindings, which should help reduce dependency install times.

chore(cu): bump deps

---

servers/cu/README.md
servers/cu/src/config.js
servers/cu/src/domain/client/metrics.js
servers/cu/src/routes/cron.js
servers/cu/src/routes/dryRun.js
servers/cu/src/routes/middleware/index.js
servers/cu/src/routes/middleware/withMetrics.js
servers/cu/src/routes/result.js
servers/cu/src/routes/results.js
servers/cu/src/routes/state.js

Closes #769 
This PR adds a middleware called `withMetrics`. Using simple function composition, we add this middleware onto each ao process-based route, which instruments the endpoint, adding it's metrics to the OpenTelemetry `/metrics` endpoint on the CU.
No additional dependencies. Just good ole' function composition.

Instrument CU http endpoints

---

connect/README.md

This PR fixes issue #547  
The current documentation on npm says
```
let { messages, spawns, output, error } = await result({
message: "l3hbt-rIJ_dr9at-eQ3EVajHWMnxPNm9eBtXpzsFWZc",
process: "5SGJUlPwlenkyuG9-xWh0Rcf0azm8XEd5RBTiutgWAg",
});
```
But with changes made to the SDK, returned values should look like 
```
let { Messages, Spawns, Output, Error } = await result({
message: "l3hbt-rIJ_dr9at-eQ3EVajHWMnxPNm9eBtXpzsFWZc",
process: "5SGJUlPwlenkyuG9-xWh0Rcf0azm8XEd5RBTiutgWAg",
});
```

docs(connect):update README #547

---

dev-cli/container/build.sh
dev-cli/container/src/aolibc/aostdio.c
dev-cli/src/versions.js

This PR is about updating the aolibc library to submit a file close to weave drive to close the file stream.

feat(dev-cli): add file close function to aolib

---

servers/ur/src/proxy.js
servers/ur/src/redirect.js

fix(ur): return 404 if process id cannot be extracted from request #790

---

connect/README.md

This is a README update to explain and show a fix for using the AOConnect package with Next.js
Closes #526

fix(connect): add note to readme about usage with Next.js

---

servers/mu/src/domain/clients/cron.js

Closes #752 
Throws an error if you try to .monitor a cron process that is already being monitored.

fix(mu): throw error when .monitor same process twice

---

connect/README.md
connect/package.json

Related to PR #792 and issue #526
This updates the exports object in the connect package.json file to add a line that Webpack looks for. This resolves cases of using Webpack in the browser for bundling which NextJS uses under the hood.
We also add an escape hatch for those using Webpack for a server application to fix issues that may be cause by webpack wanting to resolve to the browser file.
The README is updated to reflect this.

fix(connect): fix webpack module resolution for browsers

---

servers/mu/README.md
servers/mu/package-lock.json
servers/mu/package.json
servers/mu/src/config.js
servers/mu/src/domain/clients/metrics.js
servers/mu/src/domain/index.js
servers/mu/src/routes/index.js
servers/mu/src/routes/metrics.js

Closes #799 
Copied over metrics client and initial setup from CU so that the MU now also has a metrics client to start tracking metrics with and exposes a new /metrics endpoint to pull said metrics.

perf(mu): add metrics client with /metrics endpoint

---

.gitignore

My editor has some settings that has it attempting to auto fix and what not for other linting tools, this update allows anyone using visual studio code to add a `.vscode` folder with settings etc. to turn off extensions or change defaulted settings to better cooperate with the repo and ensure those settings don't get tracked in for everyone

feat: add .vscode folder to ignore list

---

servers/mu/src/routes/middleware/index.js
servers/mu/src/routes/middleware/withMetrics.js
servers/mu/src/routes/monitor.js
servers/mu/src/routes/root.js

This copies the `withMetrics` middleware from the CU and implements it across both the monitor endpoint and the root endpoint

perf(mu): add metrics middleware for http requests #802

---

servers/mu/src/domain/clients/in-memory.js
servers/mu/src/domain/index.js
servers/mu/src/domain/lib/cu-fetch-with-cache.js
servers/mu/src/domain/lib/cu-fetch-with-cache.test.js

Closes #558 
Adds a new library utility to create a fetch function that is wrapped with a handler for redirects which writes to a passed in LRU cache so that subsequent requests will have their host set explicitly to the previously redirected url for the given process id
This is intended for use with the CU since URLs to be fetched include a processId in their query parameters and this is used as the cache key.

perf(mu): cache potential CU redirect when fetching results #558

---

servers/ur/src/config.js
servers/ur/src/domain.js
servers/ur/src/domain.test.js
servers/ur/src/proxy.js
servers/ur/src/redirect.js

Closes #808 
Allows configuring `OWNER_TO_HOST` to route specific process owners to specific hosts, "bailing out" of the algorithmic host determination.
As a result `subrouter` configuration and logic is deprecated and will need to be removed later once subrouting by owner has been moved to the more flexible `OWNER_TO_HOST` functionality.

feat(ur): allow configuring ownerToHost #808

---

dev-cli/container/src/emcc-lua
dev-cli/src/versions.js

This PR builds a new AOS module with 41MB stacksize

chore: update ao build image to use 41 MB stacksize

---

servers/mu/src/domain/clients/cron.js

Closes #811 
Unable to reproduce error where procs.json was emptied out. However, added try catch to parsing of file to catch error and replace with {}. Works with empty or corrupted procs file.

fix(mu): empty procs.json error catch

---

servers/mu/src/domain/clients/cron.js

Closes #796 
Was able to recreate issue - error throws when unmonitoring an untracked process. The error message is fairly unclear, so added thrown error explaining issue. Generally, though, working as intending.

fix(mu): better error message when unmonitoring untracked processes #796

---

dev-cli/README.md

Probably "fixes" https://github.com/permaweb/ao/issues/824 ;) - the mapping in the deno.json does not contain the latest version (at the time of writing - `0.0.59`) of the CLI

docs: latest version for the dev-cli

---

servers/mu/src/domain/clients/cron.js
servers/mu/src/domain/clients/cu.js
servers/mu/src/domain/clients/gateway.js
servers/mu/src/domain/clients/scheduler.js
servers/mu/src/domain/clients/uploader.js
servers/mu/src/domain/index.js
servers/mu/src/domain/lib/with-timer-metrics-fetch.js
servers/mu/src/domain/lib/with-timer-metrics-fetch.test.js
servers/mu/src/domain/lib/with-timer-metrics.js
servers/mu/src/domain/lib/with-timer-metrics.test.js
servers/mu/src/domain/utils.js
servers/mu/src/domain/utils.test.js
servers/mu/src/routes/middleware/withMetrics.js

closes #826
This adds a new util for swallowing errors as well as a withTimingMetrics HOF that can be used to wrap and compose functions that can keep track of execution time from the start to the return of the function.

perf(mu): Implement outgoing http Metrics #826

---

servers/mu/src/domain/clients/cron.js
servers/mu/src/domain/clients/cu.js
servers/mu/src/domain/clients/gateway.js
servers/mu/src/domain/clients/scheduler.js
servers/mu/src/domain/clients/uploader.js

the histogram needs to get passed in as timer since it could be a histogram or summary or any other function that has a `startTimer` prop that returns a stop function.

fix(mu): timer dependency not passed in correctly

---

dev-cli/container/src/ao.lua

While the default AOS behavior is now to add an authority explicitly while starting a process, there is still never a reason to make processes trust everyone in absence of an authority.
For all functional purposes, a process may as well be 'dead' than open for all to access. At some point perhaps a warning/confirmation method should be implemented if the user removes the last authority? But this should be carefully thought through.
For now, this code pattern is already being accidentally copied into other implementations (see the recent cpp dev-cli library), so let's remove the potential for danger from the 'reference' implementation.

fix: In the event of having no authorities on the list, trust no-one.

---

servers/mu/src/domain/api/sendDataItem.js
servers/mu/src/domain/api/sendDataItem.test.js

Closes #731 
When spawning a process, we need to crank assignments if it is spawned with Target tags.

feat(mu): assign process if spawned with target tag #731

---

servers/mu/src/domain/lib/with-timer-metrics.js
servers/mu/src/domain/lib/with-timer-metrics.test.js

This PR adds an early error check for the timer not being passed in or passed incorrectly for the metrics timer implementation. This will allow for an early signal on server startup if there is a timer metrics use case somewhere that a timer did not get injected into correctly.

fix(mu): add error assertion for missing metrics dependency

---

servers/mu/src/domain/clients/cron.js
servers/mu/src/domain/index.js

closes #856 
adds a monitor gauge dependency to starting and terminating a cron monitor for metrics related the the number of cron monitors started at a time.

perf(mu): add cron monitor gauge metrics

---

servers/mu/src/domain/api/processSpawn.js
servers/mu/src/domain/clients/worker.js
servers/mu/src/domain/index.js

Closes #847 
On a process spawn, we need to pull the result from the cu and crank new messages / processes / assigns.

feat(mu): pull result and crank on spawn #847"

---

servers/mu/src/domain/lib/build-success-tx.js
servers/mu/src/domain/lib/pull-result.js

Breaking issue was that tx.id did not exist on context.
Deeper issue was pull-result was not properly bubbling errors. Both fixed.

fix(mu): pulling result on a process msg will now have tx id, error handling fixed

---

servers/cu/src/domain/client/ao-process.js
servers/cu/src/domain/client/ao-process.test.js

closes #804 
Adds a number of test cases to test each branch as well as the "happy path"
Adjusts the internal `recentCheckpoints` to be a dependency that defaults to a `new Map()`
Add a conditional check to verify that the Data Item has a tags array

Write test cases for saveCheckpointWith

---

scheduler-utils/src/locate.js
scheduler-utils/src/raw.js
scheduler-utils/src/utils.js
scheduler-utils/src/utils.test.js

closes #246 
adds a `trimTrailingSlash` function with a test to trim the trailing slash from the URL if it has one.
Wraps the URL returned from both `raw` and `locate` function return values.

fix(scheduler-utils): trim trailing slash from returned URLs #246

---

servers/mu/.env.example
servers/mu/README.md
servers/mu/src/config.js
servers/mu/src/domain/clients/gateway.js
servers/mu/src/domain/index.js
servers/mu/src/domain/utils.js
servers/mu/src/domain/utils.test.js

Closes #894 
This PR separates `GRAPHQL_URL` into two separate configurations:
- `ARWEAVE_URL`: the host of the Arweave http server to be used by the MU
- `GRAPHQL_URL`: the host of the Arweave GraphQL server to be used by the MU
Before these two services were conflated, when they are actually separate services.
This functionality matches the behavior of the CU, by allowing a default `GATEWAY_URL` as a default configuration fallback that is used to default both values, if not specified.
Finally, `isWallet` was refactored to use the separate `ARWEAVE_URL`, in lieu of parsing the structure of `GRAPHQL_URL`, which was not only an incorrect conflation (as described above), but brittle in the the sense that it assumed a specific structure of the string

feat(mu): separate URL configuration

---

servers/mu/src/domain/clients/cron.js
servers/mu/src/domain/clients/cron.test.js
servers/mu/src/domain/index.js

This PR adds a refactor to the init monitor HOF so that it can be tested and adds some initial tests for the init function and the "kill" function.
TODO: tests still need to be added for `startMonitoredProcessWith` and it will probably need refactored to add dependency injection to make it testable.
The "kill" function probably needs another test or may also need refactored for dependency injection to properly test it.

test(mu): add tests for cron monitor functions

---

servers/cu/package-lock.json
servers/cu/package.json
servers/cu/src/domain/client/ao-block.js
servers/cu/src/domain/client/ao-block.test.js

Closes #368 
Adds a backoff and a circuit breaker to load block metadata call. Adds tests to ensure they are working.

chore(cu): add backoff, circuit breaker to gatweay client for load block metadata

---

servers/cu/src/domain/lib/evaluate.js
servers/cu/src/domain/lib/evaluate.test.js
servers/cu/src/domain/worker/evaluate.js
servers/cu/src/domain/worker/evaluate.test.js

Closes #845 
Sends a signal when the eval stream is finished. Delete WASM instance from cache when this flag is received.

perf(cu): remove wasm instances from cache on finish #845

---

dev-cli/container/src/ao.lua

This PR modifies the handlers 2.0 API slightly:
- Allow `msg.receive` to take an alternate `From` value if necessary.
- Change `Spawn(...).after` to `Spawn(...).onReply` to match the `Send` equivalents.

Handlers 2.0 API tweaks

---

servers/cu/src/domain/client/ao-module.js
servers/cu/src/domain/lib/evaluate.js
servers/cu/src/domain/utils.js
servers/cu/src/domain/worker/evaluate.js
servers/cu/src/domain/worker/evaluator/index.js
servers/cu/src/domain/worker/evaluator/main.js

This PR makes it so that the CU will transfer the ArrayBuffer representing an ao process' memory between the main thread and worker thread. This in lieu of a structured clone being performed on the ArrayBuffer across threads -- the default behavior of comms via a MessageChannel.
This should reduce the evaluation times for all processes, but particularly processes with large memory foot prints. Additionally, this also circumvents an existing NodeJS bug that prevent structured cloning an ArrayBuffer >4GB.

fix(cu): transfer memory between worker and main thread

---

servers/cu/package-lock.json
servers/cu/package.json
servers/cu/src/domain/client/ao-module.js
servers/cu/src/domain/client/ao-module.test.js
servers/cu/src/domain/client/ao-process.js
servers/cu/src/domain/client/ao-process.test.js
servers/cu/src/domain/client/ao-su.js
servers/cu/src/domain/client/ao-su.test.js
servers/cu/src/domain/client/arweave.js
servers/cu/src/domain/client/arweave.test.js
servers/cu/src/domain/dal.js
servers/cu/src/domain/lib/hydrateMessages.js
servers/cu/src/domain/lib/hydrateMessages.test.js
servers/cu/src/domain/lib/loadMessageMeta.test.js
servers/cu/src/domain/lib/loadModule.js
servers/cu/src/domain/lib/loadModule.test.js
servers/cu/src/domain/lib/loadProcessMeta.js
servers/cu/src/domain/lib/loadProcessMeta.test.js
servers/cu/src/domain/model.js
servers/cu/src/domain/utils.js
servers/cu/src/domain/utils.test.js

Closes #862 
This PR makes it so the CU will now set fields derived from `owner` using a projection of the data, instead of straight mapping `owner.address`. This allows the CU to map `owner` to more idiomatic addresses, given the owner. For example, this PR implements setting fields to an idiomatic Ethereum address if it detects the owner is an Ethereum account
Subsequently, the CU now needs more information to determine the value of fields on `Process`, `Module`, and `Message`, and that information was not being cached on the cached records. So this PR also includes changes such that the mapping of `owner` is performed in business logic, instead of pre-cached, and the cached records will "self-migrate" such that they store the necessary data needed by the CU to perform its derivations.

feat(cu): derive address from owner

---

dev-cli/tools/build.sh

Deploy script did not create dist folder

fix: deploy script for cli

---

scheduler-utils/README.md
scheduler-utils/src/client/gateway.js
scheduler-utils/src/index.browser.js
scheduler-utils/src/index.common.js
scheduler-utils/src/index.js
scheduler-utils/src/utils.js
scheduler-utils/src/utils.test.js

Sometimes, when their is no cache value, scheduler utils needs to query the gateway for a scheduler location. If this fails, add exponential backoff.

perf(scheduler-utils): add exponential backoff to gateway requests

---

servers/cu/src/domain/api/dryRun.js
servers/cu/src/domain/api/readState.js
servers/cu/src/domain/client/metrics.js
servers/cu/src/domain/index.js
servers/cu/src/domain/lib/evaluate.js
servers/cu/src/domain/lib/evaluate.test.js

Closes #917 
This PR adds two separate but related metrics to the CU: total message evaluations and total gas used. They have added labels: processId, cron, dryRun, and error. Their are two views per metric worth visualizing: All the CUs over time, so we can see which units are doing the most evals/using the most gas; and on a per-unit (and per-process) basis, we can see what % of evals/gas are cron, dryrun, error.

perf(cu): add total evals, gas used metrics to cu #917

---

servers/su/Dockerfile

Copies necessary binaries in order to run the su binary as a docker container. Addresses https://github.com/permaweb/ao/issues/932

fix(su): fix Dockerfile so you can run su in container

---

connect/package-lock.json
connect/package.json
connect/src/index.browser.js
connect/src/index.common.js
connect/src/index.js

Title says it all. Just exposing some functionality on `connect` that was recently added to `scheduler-utils`

feat(connect): bump scheduler-utils and expose GRAPHQL_MAX_RETRIES and GRAPHQL_RETRY_BACKOFF

---

dev-cli/src/commands/exec.js

Just updated the exec.js to add correct description and rename the function to exec

refactor(dev-cli): rename build function to exec for clarity and added correct description

---

loader/package.json
loader/src/index.cjs

This PR aims to fix the out of date typings in `@permaweb/ao-loader` and updates the `package.json` file to refer to the correct declaration file.
Fixes: #873 #593

fix(loader): update types & point to the correct declaration file

---

servers/mu/src/domain/lib/build-success-tx.js
servers/mu/src/domain/lib/build-success-tx.test.js

Closes #926 
Removes 'Ao-Spawn-Success' tag being built on the MU spawn success tx.

chore(mu): remove ao-spawn-sucess from mu #926

---

servers/cu/src/domain/client/ao-su.js
servers/cu/src/domain/client/ao-su.test.js

Closes #971.
Maps signature, data, and anchor fields to return from SU loadProcess.

chore(cu): map signature, data, anchor fields in loadprocess #971

---

servers/cu/src/bootstrap.js
servers/cu/src/domain/lib/evaluate.js
servers/cu/src/effects/worker/evaluate.js
servers/cu/src/effects/worker/evaluate.test.js
servers/cu/src/effects/worker/evaluator/index.js
servers/cu/src/effects/worker/evaluator/main.js

Closes #991 
This should help reduce memory pressure of CUs due to old wasm instances no longer in use.
A progression from #845

perf(cu): broadcast to all worker threads when eval stream is closed #991

---

servers/cu/src/bootstrap.js
servers/cu/src/domain/api/dryRun.js
servers/cu/src/domain/api/readResult.js
servers/cu/src/domain/api/readState.js
servers/cu/src/domain/lib/chainEvaluation.js
servers/cu/src/domain/lib/loadProcess.js
servers/cu/src/routes/dryRun.js

Closes #984 
This also adds an optimization downstream from chaining evaluation streams: if there is overlap between chained eval streams, which can happen if many messages are sent a process and requested from the CU close together (the result calls may arrive out of order to the CU), then the CU will more likely serve that overlap from the evaluation cache rather than spin up another evaluation stream. This should help reduce resource contention for messages that have already been evaluated.
The majority of the diff in `dryRun` is just rejigging the Async chain to be more declarative. There is a bit more going on in the steps and it's more kosher to use a declarative style, so that the intent is not lost in the implementation details.

perf(cu): use cached readState on dryRun if within allowed max age #984

---

servers/cu/package-lock.json
servers/cu/package.json

This PR updates the dependencies in the CU `package.json`:
1. **@permaweb/ao-loader**: `0.0.35` → `0.0.37`
2. **@permaweb/weavedrive**: `0.0.6` → `0.0.8`
---
- The updated **AO-Loader** now includes the ability to inject metering for gas usage determination.
- The new Weavedrive update includes support for the bootloader and reading layer2 dataItems.

chore(cu): update ao-loader and weavedrive dependencies to newest versions

---

loader/src/index.cjs
loader/test/emscripten2.test.js
loader/test/index.test.js
servers/cu/src/config.js
servers/cu/src/effects/ao-module.js
servers/cu/src/effects/wasm.js

closes #1034 
Just need to publish new ao-loader package to npm and update the cu's package.json to use new version.

chore(cu/loader): Integrate WASM Metering into CU and Loader 

---

dev-cli/src/commands/publish.js
servers/cu/src/config.js

fix(dev-cli/cu): setting memory_limit issue / added module formats

---

servers/mu/src/domain/clients/gateway.js

Closes (?) #905 
Adds more retries to iswallet function. Hopefully results in less wallet errors.

fix(mu): add retries to iswallet to help with mistaken wallets

---

loader/src/index.cjs

New Metering Formats:
`wasm32-unknown-emscripten_metering` uses existing emscripten4 glue code
`wasm64-unknown-emscripten_metering` uses existing wasm64-emscripten glue code

chore(loader): introducing new formats for metering

---

connect/package-lock.json
connect/package.json
connect/src/lib/message/upload-message.js
connect/src/lib/message/upload-message.test.js
connect/src/lib/spawn/upload-process.js
connect/src/lib/spawn/upload-process.test.js
connect/src/lib/utils.js
connect/src/lib/utils.test.js

Use the new `@permaweb/protocol-tag-utils` to properly add tags to data item on `message` and `spawn`, according to the convention.
Remove subsequent dead code.

fix(connect): properly add protocol tags on message and spawn #1059

---

servers/cu/src/domain/lib/chainEvaluation.js

chore(cu): add grace window to chaining logic to allow for more performant chaining

---

servers/cu/src/effects/ao-block.js
servers/cu/src/effects/ao-block.test.js
servers/cu/src/effects/ao-evaluation.js
servers/cu/src/effects/ao-evaluation.test.js
servers/cu/src/effects/pg.js
servers/cu/src/effects/sqlite.js

Seq was being evaluated as a string, leading to incorrect orderings (ie, '0:2' > '0:15'). Fixes this to compare epoch and nonce numerically.

fix(cu): select cached messages with correct seq where clause

---

connect/src/lib/spawn/index.js

Currently aoconnect's `spawn` function's `data` option is incorrectly limited to a string type, whereas the internal implementaiton [supports ArrayBuffer types](https://github.com/permaweb/ao/blob/main/connect/src/lib/spawn/upload-process.js#L27), which is relevant when using non-text data. This small PR fixes this type.

fix(connect): support spawn data ArrayBuffer type

---

dev-cli/tools/build.sh

The output of $(dirname "$0")/.." is a relative path, which may cause an error:
```
zip I/O error: No such file or directory
```

Fix[dev-cli]: root_dir: use absolute path instead of relative path

---

loader/src/formats/wasm64-emscripten.cjs

This PR reverts a previous pr that adds a _free function to the wasm64 glue code in ao-loader. The result of that implementation did not work.

feat(loader): revert free call in wasm64

---

connect/esbuild.js
connect/package-lock.json
connect/package.json
connect/src/client/browser/wallet.js
connect/src/client/hb.js
connect/src/client/node/wallet.js
connect/src/index.browser.js
connect/src/index.common.js
connect/src/index.js

This PR adds a "HyperBEAM mode" to `aoconnect`:
```js
import { connect } from 'aoconnect'
const { message, createDataItemSigner, ... } = connect.hb({ wallet, URL: 'your-hb-node' })
```
This will relay all HTTP request through the HyperBEAM relay device on the HyperBEAM node at `URL`. In addition, `createDataItemSigner` returned from `connect.hb()` will always sign ANS-104 data items with the wallet confgured to sign HyperBEAM HTTP messages.
Vast majority of the diff is the lockfile and then re-indenting the `index.common.js` file, since the entrypoint is wrapped with an additional layer in order to pass in the platform-specific signer impls. Note none of the core logic needed to change, just the entrypoints and the thin hb relay wrapper around `fetch`

feat(connect): add connect.hb() to use HyperBEAM mode

---

servers/mu/src/app.js
servers/ur/src/app.js

When a process is stopped using a signal (`SIGTERM` with `systemd` for example), it should be stopped using `process.exit()` function. If not, the node process will still be running and a `SIGKILL` will be required to stop it.

Process must exit when receiving SIGTERM

---

servers/su/src/domain/clients/store.rs

This bug has always existed in the SU but hash chain verification surfaced it. The process and its assignment were being returned when the from cursor was the process timestamp. When hash chain verification was enabled, this caused spawns to fail.
This does mean that if this is put in testnet, Processes that got evaluated with the process message twice before will now only get it once if cold started.

fix(su): fix su returing process on first from

---

servers/cu/src/domain/lib/evaluate.js

I think this will finally do it.
For some reason, even `pipeline` Promise won't resolve if all the underlying streams are destroyed. So this PR uses `Promise.race` to ensure the error bubbles and ensures all streams are destroyed and all listeners are removed to prevent race conditions.

fix(cu): prevent stuck stream by destroying all and bubbling error

---

connect/src/index.common.js

Updated connect to use default urls for relay and main mode

feat(connect): set defaults for relay and mainmode

---

connect/README.md
connect/src/client/ao-mu.js
connect/src/dal.js
connect/src/index.common.js
connect/src/lib/message/index.js
connect/src/lib/message/upload-message.js
connect/test/e2e/node-esm/index.test.js
connect/test/e2e/package.json

This PR adds two new APIs to aoconnect. The first is a signMessage method which takes the same arguments passed to message, however only returns a signed data item / http message. The second method added is sendSignedMessage, which takes the previously created signed data item / http message and performs the dispatch of the message.

feat: create standalone signer / dispatch APIs (signMessage / sendSignedMessage)

---

connect/src/lib/request/index.js

This PR prevents errors when handling responses lacking a 'Content-Type' header. A null check ensures the application gracefully handles these cases, improving robustness.

fix: need to check for null on content-type

---

loader/package.json
loader/src/index.cjs
loader/test/loader.test.js
package.json

Allows passing memory by reference which leads to a big performance improvement.

Introduce unsafe mode
