permaweb/ao

connect/package-lock.json, connect/package.json, connect/src/client/ao-su.js, connect/src/client/ao-su.test.js, connect/src/index.common.js
=> feat(connect): cache process meta in LRU in-memory cache #511

dev-cli/container/src/emcc-lua, dev-cli/src/versions.js
Changed emscripten build back to Os - was set to O0 for debugging.
=> fix: fixed emcc to use Os instead of O0

dev-cli/container/src/ao.lua, dev-cli/src/versions.js
merging tags needs to exclude required data-item properties
=> fix: tag normalization bug

servers/mu/src/domain/lib/processSpawn/build-success-tx.js, servers/mu/src/domain/lib/processSpawn/build-success-tx.test.js, servers/mu/src/domain/utils.js, servers/mu/src/domain/utils.test.js
=> feat(mu): include spawned tags on spawn success message sent to spawner #522

connect/src/index.common.js, connect/src/lib/message/index.js, connect/src/lib/monitor/index.js, connect/src/lib/unmonitor/index.js
=> chore(connect): remove locating scheduler on message monitor and unmonitor #534

servers/cu/src/domain/client/ao-block.js, servers/cu/src/domain/client/arweave.js, servers/cu/src/domain/client/arweave.test.js, servers/cu/src/domain/client/worker.js, servers/cu/src/domain/utils.js, servers/cu/src/domain/utils.test.js
=> feat(cu): allow GATEWAY_URL to have static path and query params #551

connect/README.md, connect/package-lock.json, connect/package.json, connect/src/client/gateway.js, connect/src/client/gateway.test.js, connect/src/index.browser.js, connect/src/index.common.js, connect/src/index.js, connect/src/lib/utils.js, connect/src/lib/utils.test.js
Also add a little error handling on gateway comms.
=> Add `GRAPHQL_URL` to connect and pass down to `scheduler-utils`

servers/cu/README.md, servers/cu/package-lock.json, servers/cu/package.json, servers/cu/src/config.js, servers/cu/src/domain/client/ao-block.js, servers/cu/src/domain/client/ao-block.test.js, servers/cu/src/domain/client/arweave.js, servers/cu/src/domain/client/arweave.test.js, servers/cu/src/domain/client/worker.js, servers/cu/src/domain/index.js, servers/cu/src/domain/model.js, servers/cu/src/domain/utils.js, servers/cu/src/domain/utils.test.js
=> feat(cu): allow passing GRAPHQL_URL and ARWEAVE_URL separately. Refactor usages #551

servers/cu/src/domain/lib/hydrateMessages.js
Closes #577 
The requests are hanging because the promise to be resolved when the evaluation stream ends are not resolving due to the stream itself never ending. Nginx would eventually timeout at 60 seconds with a 504.
These changes cause the stream to be ended properly on error, and so the promise will ultimately resolve or reject (though not entirely sure why -- some more NodeJS pipeline dragons).
=> fix(cu): workaround to properly end stream when error received from SU stream #577

servers/cu/src/domain/lib/hydrateMessages.js, servers/cu/src/domain/lib/hydrateMessages.test.js
=> chore(cu): remove support for Load messages #607

servers/cu/src/domain/client/ao-su.js, servers/cu/src/domain/client/ao-su.test.js
=> chore(cu): remove legacy su response handling #570

servers/cu/src/domain/client/ao-su.js, servers/cu/src/domain/client/ao-su.test.js, servers/cu/src/domain/client/arweave.js, servers/cu/src/domain/client/arweave.test.js, servers/cu/src/domain/dal.js, servers/cu/src/domain/lib/hydrateMessages.js, servers/cu/src/domain/lib/hydrateMessages.test.js, servers/cu/src/domain/model.js
=> feat(cu): allow excluding fields on assigned messages #625

.github/workflows/cu.yml, .github/workflows/mu.yml, .github/workflows/su.yml
Addressing https://github.com/permaweb/ao/issues/646
Dependent on https://github.com/permaweb/ao/pull/650
=> feat(images): publish public docker images for mu/cu/su

servers/cu/src/domain/api/dryRun.js, servers/cu/src/routes/dryRun.js
After some discussion, we are reversing these changes, until a consensus is had.
This reverts commit 08f0cc5bca61f856a7ba1d11bc30fbe529e8f047.
=> feat(cu): revert dryRun changes #674

servers/cu/src/domain/client/ao-su.js, servers/cu/src/domain/client/ao-su.test.js, servers/cu/src/domain/lib/loadMessages.js
Closes #686 
This PR adds of generic `backoff` utility to all SU apis.
Perhaps we could the `maxRetries` and `delay` configurable if that was some folks found useful.
=> perf(cu): add retry with exponential backoff to all SU apis #686

servers/cu/src/domain/lib/evaluate.js
=> perf(cu): limit size of eval stream cron cache to prevent unbounded memory consumption #690

servers/cu/src/domain/lib/loadModule.js, servers/cu/src/domain/lib/loadModule.test.js
=> feat(cu): parse extensions and options tags #698

servers/cu/README.md, servers/cu/src/config.js, servers/cu/src/domain/client/wasm.js, servers/cu/src/domain/index.js, servers/cu/src/domain/lib/loadModule.js, servers/cu/src/domain/lib/loadModule.test.js, servers/cu/src/domain/model.js
=> feat(cu): make supported module formats and extensions configurable and check #700

servers/cu/README.md, servers/cu/src/config.js, servers/cu/src/domain/client/ao-process.js, servers/cu/src/domain/index.js, servers/cu/src/domain/lib/loadProcess.js, servers/cu/src/domain/lib/loadProcess.test.js, servers/cu/src/domain/model.js
=> feat(cu): add ALLOW_OWNERS config and check when loading process #704

loader/src/formats/wasm64-emscripten.cjs, loader/src/index.cjs, loader/test/aos64/aos64.test.cjs
Fixed issue with resizeHeap mapping to Module
=> feat: add resizeHeap to Module

connect/src/lib/results/index.js
=> fix(connect): use correct type in results JSDoc #714

connect/README.md, connect/src/index.browser.js, connect/src/index.common.js, connect/src/index.js, connect/src/lib/serializeCron/index.js, connect/src/lib/serializeCron/serialize-cron.test.js
Closes #206 
Creates util function serializeCron which takes in a Cron Object and returns AO DataProtocol compliant tags.
=> feat(connect): add serializeCron util function to connect

servers/cu/README.md, servers/cu/package-lock.json, servers/cu/package.json, servers/cu/src/config.js, servers/cu/src/domain/client/ao-process.js, servers/cu/src/domain/client/metrics.js, servers/cu/src/domain/index.js, servers/cu/src/routes/index.js, servers/cu/src/routes/metrics.js
This PR implements the pipeline for instrumenting the CU and adds the first application level metric: number of processes running on the CU
=> perf(cu): instrument runtime metrics and add ao process count metric #748

dev-cli/README.md
=> fix: README commands updates

servers/cu/src/domain/index.js
=> perf(cu): dry-runs use a separate worker thread pool #753

servers/cu/package-lock.json, servers/cu/package.json
Bump ao-loader to support closing file handles in weave drive
=> chore(cu): bump ao-loader and weavedrive

servers/mu/README.md, servers/mu/package-lock.json, servers/mu/package.json, servers/mu/src/config.js, servers/mu/src/domain/clients/sqlite.js, servers/mu/src/domain/clients/taskQueue.js, servers/mu/src/domain/clients/worker.js, servers/mu/src/domain/index.js
Addresses #661 Part 2 - Queue Persistance.
Persist task queue in sqlite database across lifecycles.
=> fix(mu): message reliability  persist task queue

servers/mu/src/domain/index.js
fixes an issue of a missing dependency on histogram being passed to `writeAssignmentWith`
=> fix(mu): pass missing histogram dependency

servers/cu/src/domain/client/ao-process.js, servers/cu/src/domain/index.js
There is a scenario where a drained cache entry could be evicted from the LRU cache, despite not taking up much space, and subsequently bring lost forever.
So this PR moves the drained entries to a separate internal `Map`, so that they're not considered as eviction candidates, and can effectively live for as long as the application is running (hopefully across application restarts eventually see #843)
Since two internal Maps are being used, we had to also tweak some of the apis exposed, mainly the ones to do with iterating the entries (basically concatenating internally then iterating) and stats concerning usage (again just summing each stat from each internal cache `Map`)
=> chore(cu): move drainedToFile entries to separate map, as to not be evicted from LRU and lost

servers/cu/src/domain/worker/evaluate.js, servers/cu/src/domain/worker/evaluate.test.js
=> fix(cu): delete cached WebAssembly.Instance on evaluations that produce an error #853

servers/cu/src/domain/api/readState.js, servers/cu/src/domain/lib/chainEvaluation.js
=> perf(cu): wrap chainEvaluation with lock to prevent duplicate work #844

.github/workflows/su.yml
This was a copy/pasta that is causing publishing images to fail.
=> fix(su): update su github to publish to permaweb ghcr

servers/mu/src/domain/api/processSpawn.js, servers/mu/src/domain/index.js, servers/mu/src/domain/lib/spawn-process.js
closes #855 
Fetches Module Id from the SU, replaces module tags with that ID.
=> fix(mu): add module tags to spawn #855

dev-cli/README.md
closes #794 
updates the readme to reflect what building a wasm actually produces
=> docs(dev-cli): update docs to reflect changes made to building wasm

connect/package-lock.json, connect/package.json
=> chore(connect): bump deps

dev-cli/container/src/ao.lua, dev-cli/src/versions.js
Fixed typo in ao.lua for `ao.send` for `.receive` and `.onReply`
=> fix: update ao receive and onReply to use x-reference

dev-cli/container/src/ao.lua, dev-cli/container/src/json.lua, dev-cli/container/src/loader.lua, dev-cli/src/versions.js
Fix bug in ao.lua - reference was being set as a number not a string in the pattern match function
=> fix: bug with ao receive

servers/mu/src/domain/clients/metrics.js, servers/mu/src/domain/clients/worker.js, servers/mu/src/domain/index.js, servers/mu/src/domain/lib/handle-worker-queue-message.js
Closes #918 
Fixes the implementation of the worker queue size metric implementation in the MU. Now, returns the max queue size in the last minute.
=> fix(mu): stop queue size metric from becoming negative

servers/cu/src/domain/api/dryRun.js, servers/cu/src/domain/api/perf.js, servers/cu/src/domain/api/readState.js, servers/cu/src/domain/client/ao-process.js, servers/cu/src/domain/client/metrics.js, servers/cu/src/domain/index.js, servers/cu/src/domain/lib/evaluate.js
This PR refactors `collect` on gauge such that it can emit multiple values, using multiple labels. Each set of labels produce a timeseries.
As a result, some usages are refactored, gauges combined, and labels refined.
=> perf(cu): finer metrics and better usage of gauges

.github/workflows/dev-cli.yml, dev-cli/deno.json, dev-cli/deno.lock, dev-cli/src/commands/init.js, dev-cli/src/deps.js, dev-cli/tools/build.sh, dev-cli/tools/create-install-script.js, dev-cli/tools/deploy/index.js, dev-cli/tools/deploy/package-lock.json, dev-cli/tools/deploy/package.json, dev-cli/tools/update-tx-mappings.js, dev-cli/tools/update-version.js
- consolidate deps into `deps.js`
- ignore lockfile when running certain scripts
- add `allow_env` to command to compile binaries
- update the CI to use the `ar.io` sdk to update the ArNS for `install_ao` undername
=> dev-cli improvements

servers/mu/src/domain/clients/cron.js, servers/mu/src/domain/clients/cron.test.js, servers/mu/src/domain/clients/sqlite.js, servers/mu/src/domain/index.js
Closes #950
Implements a sqlite DB for saving cron processes
=> feat(mu): move procs.json to a sqlite implementation

servers/mu/src/domain/api/sendAssign.js, servers/mu/src/domain/api/sendDataItem.js, servers/mu/src/routes/root.js
Renames crank to push for logs for the tracer
=> chore(mu): rename crank to push for logs

servers/mu/src/domain/api/sendDataItem.js, servers/mu/src/domain/api/sendDataItem.test.js
Closes #731 
Looks for target on dataItem rather than in tags
=> fix(mu): crank assign when target received on spawn

servers/mu/src/domain/clients/cron.js, servers/mu/src/domain/clients/cron.test.js, servers/mu/src/domain/index.js
Initialize cron monitor metric to the amount of crons in the procs file on start.
=> fix(mu): initialize cron monitor metric on start

servers/mu/src/domain/clients/cron.js, servers/mu/src/domain/index.js
Does a little sqlite magic to remove old traces and stay below allocated memory limit.
=> fix(mu): delete rows from trace db based on overflow

servers/mu/src/domain/clients/cron.js, servers/mu/src/domain/clients/sqlite.js, servers/mu/src/domain/clients/worker.js, servers/mu/src/domain/index.js, servers/mu/src/domain/lib/handle-worker-metrics-message.js
Optimizing changes:
Move deletion of old traces to worker thread (non-blocking)
Make it only run once per hour
Add timestamp index to trace db
=> chore(mu): optimize delete old traces

dev-cli/container/Dockerfile, dev-cli/container/src/ao-build-module, dev-cli/container/src/ao_module_lib/config.py
=> feat(dev-cli): Ability to build 32bit and 64bit modules

loader/package-lock.json, loader/package.json, loader/src/formats/wasm64-emscripten.cjs, loader/src/index.cjs, loader/test/index.test.js
=> chore(loader): update dependencies and add wasm-metering #1016

dev-cli/container/Dockerfile, dev-cli/container/src/ao-build-module, dev-cli/container/src/ao_module_lib/libraries.py, dev-cli/container/src/aolibc/aostdio.c, loader/src/formats/emscripten4.cjs, loader/src/formats/wasm64-emscripten.cjs
Added a function to get `gasUsed` in aolibc that can be called from lua by requiring the metering lib.
```lua
local metering = require('metering')
return metering.gasUsed()
```
=> feat(dev-cli): added a gasused function to aolibc thats exposed to lua

servers/mu/src/domain/clients/taskQueue.js
Currently, we are seeing old tasks in the tasks DB that were not dequeued. We need to add a condition to remove tasks over an hour old on dequeue and startup. Additionally, we will vacuum to reallocate memory.
=> fix(mu): delete old tasks that leak into db

loader/src/index.cjs
disabled wasm metering in ao-loader
=> chore(loader): disable metering

loader/src/index.cjs
=> feat(loader): set blockHeight in handler, based on current message #1055

servers/cu/src/effects/db.js
This fix enables pg client to connect to encrypted pg databases
=> fix(cu): pg ru should connect via ssl

servers/cu/src/bootstrap.js
Add 5 retries to gateway backoff in scheduler utils
=> feat(cu): add backoff to sched-utils backoff

servers/mu/README.md
nit: fix minor typo for messenger
=> Update README.md to fix minor typo

connect/package-lock.json, connect/package.json, connect/src/client/ao-su.js, connect/src/client/ao-su.test.js, connect/src/client/hb-encode.js, connect/src/client/hb.js, connect/src/client/hb.test.js, connect/src/index.common.js, connect/src/lib/message-id/index.js, connect/src/lib/process-id/index.js, connect/src/lib/request/dispatch.js, connect/src/lib/request/format.js, connect/src/lib/request/index.js, connect/src/lib/request/transform.js, connect/test/e2e/m0/balance.test.js, connect/test/e2e/m0/exch.test.js, connect/test/e2e/m0/post.test.js, connect/test/e2e/m0/request.test.js, connect/test/e2e/m0/slot.test.js, connect/test/e2e/m2/request.test.js
This PR adds two functions for mainnet mode
* getMessageById - `const result = await getMessageById({messageId: MESSAGE, processId: PROCESS})`
* getLastSlot - `const slot = await getLastSlot({ processId: PROCESS })`
=> Feat m2 push

servers/mu/README.md, servers/mu/package.json, servers/mu/src/config.js, servers/mu/src/domain/clients/gateway.js, servers/mu/src/domain/index.js
Uses sched-utils getProcess for fetching process messages.
TODO: Once #1246 is merged, bump sched-utils in package.json
=> feat(mu): use sched-utils getProcess for processes
